# Levantaremos un servidor mariadb y un phpMyadmin
# 1º serviciso , volumen , red

services:
  basededatos:
    #Servidor MariaDB
    image: mariadb
    # Aqui vendria la etiqueta
    container_name: serv_mariadb
    ports: ["3306:3306"]
    environment:
      - MARIADB_ROOT_PASSWORD=asd1
    volumes:
      - volume1:/var/lib/mysql
    networks:
      - red_basedatos # Conectar a la red creada
  # PhpMyAdmin
  phpmyadmin:
    #    image: phpmyadmin
    build: ./phpmyadmin/ # Ejecuta el dockerfile y lo configura con las ordenes
    container_name: phpmyadmin
    ports: ["80:80", "443:443"]
    depends_on:
      - basededatos
    environment:
      - PMA_ARBITRARY=1
    networks:
      - red_basedatos # Conectar a la red creada
volumes:
  volume1:
  # - volumen1:/var/lib/mysql # Aquí se monta el volumen

networks:
  red_basedatos:
